# Generated by Django 5.0 on 2023-12-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_created_at_alter_recipe_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_plublished',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
